package de.warsteiner.jobs.utils.objects;

public enum GUIType {

	MAIN, CONFIRM, SETTINGS, STATS_SELF, STATS_OTHER,
	LANGUAGE,HELP,EARNINGS_ALL, EARNINGS_JOB, LEVELS,REWARDS,WITHDRAW,CONFIRM_WITHDRAW, CONFIRM_LEAVE;
 
}
