package de.warsteiner.jobs.utils;

public enum JobAction {

	BREAK, PLACE, KILL_MOB, FISH, FARM, MILK, CRAFT, SHEAR, ADVANCEMENT, EAT, HONEY, STRIPLOG, TAME, MMKill, BREED, DRINK, COLLECTBERRYS, 
	MMORES_BREAK;
 
}
