package de.warsteiner.jobs.utils;

public enum JobAction {

	BREAK, PLACE, KILL_MOB, FISH, FARM_BREAK, FARM_GROW, MILK, CRAFT, SHEAR, ADVANCEMENT, EAT, HONEY, STRIPLOG, TAME, BREED, DRINK, COLLECTBERRYS, 
	KILL_BY_BOW, GROWSAPLINGS, MMKILL, TNT;
 
}
