package de.warsteiner.jobs.utils;

public enum JobAction {

	BREAK, PLACE, KILL_MOB, FISH, FARM_BREAK, FARM_GROW, MILK, CRAFT, SHEAR, ADVANCEMENT, EAT, HONEY, STRIPLOG, TAME, BREED,  COLLECTBERRYS, 
	KILL_BY_BOW, GROWSAPLINGS, MMKILL, FIND_TREASURE, TRADE_EMERALDS, SMELT, EXPLORE_CHUNK, ENCHANT, DRINK_POTION;
 
}
